# Generated by Django 3.1.2 on 2020-10-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productoVenta',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad', models.CharField(max_length=3)),
                ('precio', models.CharField(max_length=4)),
                ('codigo', models.CharField(max_length=13)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
